DBZ-4777 Fix connection validation SQL syntax
removed semicolon that caused 'ERROR Failed testing connection for jdbc:db2://db2server:50000/test with user 'db2inst1' (io.debezium.connector.db2.Db2Connector)
com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=;;ROM sysibm.sysdummy1;END-OF-STATEMENT, DRIVER=[3.72.54]' error